### ISSUE TITLE
Absolute true wind direction

### ISSUE THREAD

**Issue by jonjonr6** [sankeysoft/nmea_dashboard#14]
I wasn't sure whether to open a new "issue" or re-open the "closed" one.
Thanks for fixing the MWV sentence problem. I've tested it and it works fine, but..... 

You have now made the app respond to MDA  for true wind direction. However although this works (with test data) it is an obsolete sentence. It's not on the NMEA v4.11 list and isn't transmitted by my (ancient) Raymarine ST6000 kit. Maybe it is transmitted by your kit?

I realise that this is a bit of an odd sentence because the true wind direction has to be "calculated" by the networked instruments with a heading signal (or at least a COG although that wouldn't be any use when stationary).

I think that MWD is probably the correct sentence to use for true wind direction/speed. This is on the current approved sentences list and has been for a long time.

"MWD - Wind Direction & Speed 
The direction from which the wind blows across the earth’s surface, with respect to north, and the speed of the wind. 
$--MWD,x.x,T,x.x,M,x.x,N,x.x,M*hh<CR><LF> 
Wind direction, 0 to 359 degrees True
Wind direction, 0 to 359 degrees Magnetic 
Wind speed, knots 
Wind speed, meters/second"

Thanks for the app!

**Comment by jonjonr6** [comment]
My nmea info is not the latest but you can find a download link to nmea version 4.0 if you search iec 61162-1:2010 pdf which is the same document. I think there are probably just two more recent updates after this.
You can also find a list of the up-to-date valid sentence descriptions by searching nmea 4.11 sentence descriptions pdf.
I'm assuming that it's ok to post the above but probably not the documents.

**Comment by jodysankey** [comment]
Thanks for the tip.

OK, MWD is now supporting in 0.3.9 which released today. Feel free to keep raising bugs for anything else.

If you have the time also I'd really appreciate it if you could rate or review the app in Google Play store. I don't want to nag people inside the app but the downside of not doing that is only 2 people have reviewed it!
