### ISSUE TITLE
Grid lines on history run charts

### ISSUE THREAD

**Issue by MHGBlue** [sankeysoft/nmea_dashboard#15]
The history chart would be more useful for large scale ranges with a few horizontal grid lines (I suggest 3, splitting the vertical into quarters). For example, an apparent wind speed history with a range of 0-20 knots makes it hard to tell how the wind has changed.
Vertical grid lines may also be helpful and could be static or dynamic (each vertical lines representing a specific time).

**Comment by jodysankey** [comment]
The history chart does already have horizontal (and vertical) grid lines once the chart is large enough to label those lines. On a phone screen that's typically 2 graphs on a page, on a tablet maybe 6 or 8. One of the screenshots on [play store](https://play.google.com/store/search?q=nmea+dashboard&c=apps&hl=en_US&gl=US) shows this in action.

The grid lines are always on multiples of 1, 2, or 5 multiplied by a power of ten, but the charts are autoscaling so as new data comes in the min and max will change and therefore the values of the lines can also change. I feel its very important for each line to be labeled to avoid mistakes in interpretation when that happens.

**Comment by MHGBlue** [comment]
Thank you for the update. I can see that now when I have only a few graphs on a page.

And thanks for making a useful application!
