### ISSUE TITLE
Cannot connect tcp

### ISSUE THREAD

**Issue by mikewestonip** [sankeysoft/nmea_dashboard#5]
21:37:48 INFO Starting TCP stream on InternetAddress('192.168.4.1', IPv4):3000
21:37:55 WARNING Exception opening TCP stream on InternetAddress('192.168.4.1', IPv4):3000: SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 192.168.4.1, port = 42752

**Comment by jodysankey** [comment]
This is basically Android saying it couldn't connect to the address and port you specified in the network form.

Please could you confirm the settings are correct and whatever you're aiming to connect to is on the same network. Its also good to confirm some other computer can successfully connect - telnet is useful for this, e.g. "telnet 192.168.4.1 3000". If another computer or app connects fine could you tell me what the make and model is of the thing you're connecting to?

**Comment by jodysankey** [comment]
I added a more explicit error message here that prompts the user to check their network settings so closing out the bug.
