### ISSUE TITLE
Log file. 

### ISSUE THREAD

**Issue by mikewestonip** [sankeysoft/nmea_dashboard#6]
While the debug log is great, it would be helpful to see all incoming data.  I am broadcastingany msg types on udp, but virtually none show on the dashboard.  It would be helpful to see what is actually coming in.

**Comment by jodysankey** [comment]
Thanks for trying the app and for taking the time to write feedback.

I did experiment with dumping all traffic when I was first developing but the volume of traffic on a modern boat makes the log unusable. The compromise I settled with is (approximately) every 5 minutes the app prints the total number of messages received of each time. If you leave the app running for 5 minutes this should let you see which messages have been successfully processed and which have been dropped.

**Comment by jodysankey** [comment]
Closing this out based on the previous response that the incoming message counts are logged every 5 minutes
